# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import utils.bigint
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0004_loja_id_loja_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', utils.bigint.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('info', jsonfield.fields.JSONField()),
                ('dt_criado', models.DateTimeField()),
                ('dt_visto', models.DateTimeField(null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Loja')),
            ],
        ),
    ]
