# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 11:30
from __future__ import unicode_literals

from django.db import migrations
from loja.models import *


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0002_notificacao_cliente')
    ]

    operations = [
        migrations.RunSQL('alter table notificacao_notificacao drop foreign key notificacao_notificacao_loja_id_42ecb7c7_fk_loja_loja_id;')
    ]
