# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 11:30
from __future__ import unicode_literals

from django.db import migrations
from loja.models import *


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_bigint_20161110_0004'),
        ('notificacao', '0004_auto_20161110_0008')
    ]

    operations = [
        migrations.RunSQL('alter table notificacao_notificacao add constraint notificacao_notificacao_loja_id_42ecb7c7_fk_loja_loja_id FOREIGN KEY (loja_id) REFERENCES loja_loja (id);')
    ]
