# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20161203_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_senha',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='token_senha'),
        ),
    ]
