# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'bairro'),
        ),
        migrations.AddField(
            model_name='loja',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name=b'cep'),
        ),
        migrations.AddField(
            model_name='loja',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'endereco'),
        ),
        migrations.AddField(
            model_name='loja',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', unique=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'nome_contato'),
        ),
        migrations.AddField(
            model_name='loja',
            name='telefone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'telefone1'),
        ),
        migrations.AddField(
            model_name='loja',
            name='telefone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'telefone2'),
        ),
    ]
