# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20160711_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
