# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_auto_20160711_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='id_loja_facebook',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name=b'id_loja_facebook'),
        ),
    ]
