# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_loja_id_loja_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr_problemas', models.TextField(blank=True, null=True, verbose_name=b'descr_problemas')),
                ('problemas', jsonfield.fields.JSONField(blank=True, null=True, verbose_name=b'problemas')),
            ],
        ),
        migrations.AddField(
            model_name='loja',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'cidade'),
        ),
        migrations.AddField(
            model_name='loja',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'complemento'),
        ),
        migrations.AddField(
            model_name='loja',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'email'),
        ),
        migrations.AddField(
            model_name='loja',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name=b'estado'),
        ),
        migrations.AddField(
            model_name='loja',
            name='outro_tipo_loja',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'outro_tipo_loja'),
        ),
        migrations.AddField(
            model_name='loja',
            name='tipo_loja',
            field=models.CharField(blank=True, choices=[(b'bar', b'Bar'), (b'restaurante', b'Restaurante'), (b'lanchonete', b'Lanchonete'), (b'hotel', b'Hotel'), (b'padaria', b'Padaria'), (b'outro', b'Outro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='cep',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name=b'cep'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Loja'),
        ),
    ]
