# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20161108_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='telefone1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'telefone1'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='telefone2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'telefone2'),
        ),
    ]
