# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 11:30
from __future__ import unicode_literals

from django.db import migrations
from loja.models import *


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_auto_20161109_1004')
    ]

    operations = [
        migrations.RunSQL('alter table loja_questionario drop foreign key loja_questionario_loja_id_6513d7e6_fk_loja_loja_id;')
    ]
