# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 11:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import utils.bigint


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_dropfk_20161110_0003'),
        ('dashboard', '0004_dropfk_20161110_0000'),
        ('notificacao', '0003_dropfk_20161110_0007'),
        ('pedido', '0009_dropfk_20161110_0010'),
        ('upload_cardapio', '0003_dropfk_20161110_0013')
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='id',
            field=utils.bigint.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
