# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 11:30
from __future__ import unicode_literals

from django.db import migrations
from loja.models import *


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_fkbigint_20161110_0005')
    ]

    operations = [
        migrations.RunSQL('alter table loja_questionario add constraint loja_questionario_loja_id_6513d7e6_fk_loja_loja_id FOREIGN KEY (loja_id) REFERENCES loja_loja (id);')
    ]
