# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 01:51
from __future__ import unicode_literals

from django.db import migrations
import utils.bigint


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_addfk_20161110_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='id',
            field=utils.bigint.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
