# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_auto_20161110_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name=b'cnpj'),
        ),
        migrations.AddField(
            model_name='loja',
            name='nome_estabelecimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'nome_estabelecimento'),
        ),
        migrations.AddField(
            model_name='loja',
            name='token_login',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'token_login'),
        ),
    ]
