# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-04 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_auto_20161201_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='app_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=b'app_id'),
        ),
    ]
