# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.bigint


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_loja_app_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', utils.bigint.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='loja',
            name='app_id',
        ),
        migrations.AddField(
            model_name='apps',
            name='loja',
            field=utils.bigint.BigForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Loja'),
        ),
    ]
