# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_apps_ativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loja.Loja')),
            ],
        ),
        migrations.CreateModel(
            name='DemoSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loja.Loja')),
            ],
        ),
    ]
