# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.bigint


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_apps_ativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoEmail',
            fields=[
                ('loja', utils.bigint.BigOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loja.Loja')),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoSms',
            fields=[
                ('loja', utils.bigint.BigOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loja.Loja')),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
