# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-27 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0002_estado_sigla_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='sigla_uf',
            field=models.CharField(max_length=2, verbose_name='sigla_uf'),
        ),
    ]
