# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.bigint


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', utils.bigint.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('nome_cartao', models.CharField(max_length=100, verbose_name='nome_cartao')),
                ('bandeira', models.SmallIntegerField(verbose_name='bandeira')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteMarviin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cliente_marviin', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='cpf')),
                ('authorization_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='authorization_code')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', utils.bigint.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=200, verbose_name='endereco')),
                ('complemento', models.CharField(max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('cep', models.CharField(max_length=15, verbose_name='cep')),
                ('estado', models.CharField(max_length=2, verbose_name='estado')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('tipo', models.SmallIntegerField(verbose_name='tipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
