# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_marviin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='padrao',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
