# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_marviin', '0003_clientemarviin_mail_mkt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=128)),
                ('authorization_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookTemp',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('redirect_uri', models.CharField(blank=True, max_length=700, null=True)),
                ('account_linking_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
