# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_marviin', '0004_facebook_facebooktemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='perm_not_granted',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facebook',
            name='skip_perm',
            field=models.BooleanField(default=False),
        ),
    ]
