# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_marviin', '0006_facebook_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='user',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='user',
        ),
    ]
