# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_marviin', '0007_auto_20161216_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='user',
            field=models.ForeignKey(default='ef1a9478-ebea-45b8-bc91-be18692aad33', on_delete=django.db.models.deletion.CASCADE, to='cliente_marviin.Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='user',
            field=models.ForeignKey(default='ef1a9478-ebea-45b8-bc91-be18692aad33', on_delete=django.db.models.deletion.CASCADE, to='cliente_marviin.Facebook'),
            preserve_default=False,
        ),
    ]
