# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'nome')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name=b'telefone')),
            ],
        ),
    ]
