# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='chave_telegram',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name=b'chave_telegram'),
        ),
    ]
