# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_chave_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='chave_facebook',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name=b'chave_facebook'),
        ),
    ]
