# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20160918_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'foto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'telefone'),
        ),
    ]
