# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20160929_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_interacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mensagens',
            field=models.IntegerField(default=0, verbose_name=b'numero'),
        ),
    ]
