# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20161006_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'genero'),
        ),
    ]
