# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_marviin', '0001_initial'),
        ('cliente', '0009_cliente_id_loja_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_marviin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente_marviin.ClienteMarviin'),
        ),
    ]
