# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_cliente_pedido_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_loja_facebook',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=b'id_loja_facebook'),
        ),
    ]
