# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_auto_20161210_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_marviin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente_marviin.Facebook'),
        ),
    ]
