# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20160711_2234'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.Loja', unique=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'nome'),
        ),
    ]
