# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_addfk_20161110_0002'),
        ('dashboard', '0004_dropfk_20161110_0000'),
    ]

    operations = [
    ]
