# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-26 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=30, verbose_name='nome_cidade')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estados.Estado')),
            ],
        ),
    ]
