# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fb_acesso',
            fields=[
                ('page_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('page_access_token', models.CharField(max_length=500)),
            ],
        ),
    ]
