# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import utils.bigint


class Migration(migrations.Migration):

    dependencies = [
        ('fb_acesso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbContasUsuario',
            fields=[
                ('id', utils.bigint.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('app_scoped_user_id', models.CharField(max_length=128)),
                ('page_id', models.CharField(max_length=128)),
                ('page_name', models.CharField(max_length=100)),
                ('page_access_token', models.CharField(max_length=500)),
            ],
        ),
    ]
