# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_acesso', '0002_fbcontasusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='fb_acesso',
            name='app_scoped_user_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
