# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_acesso', '0004_fb_webhook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fb_webhook',
        ),
    ]
