# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='pagina',
            field=models.IntegerField(default=0),
        ),
    ]
