# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 11:30
from __future__ import unicode_literals

from django.db import migrations
from loja.models import *


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cardapio', '0002_cardapio_pagina')
    ]

    operations = [
        migrations.RunSQL('alter table upload_cardapio_cardapio drop foreign key upload_cardapio_cardapio_loja_id_5f31376b_fk_loja_loja_id;')
    ]
