# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cardapio', '0003_dropfk_20161110_0013'),
        ('upload_cardapio', '0005_addfk_20161110_0015'),
    ]

    operations = [
    ]
