# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('loja', '0003_auto_20160711_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'produto')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name=b'valor')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name=b'quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0, verbose_name=b'numero')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name=b'valor')),
                ('formapagamento', models.CharField(blank=True, choices=[(b'credito', b'Cr\xc3\xa9dito'), (b'debito', b'D\xc3\xa9bito'), (b'dinheiro', b'Dinheiro'), (b'cheque', b'Cheque')], max_length=20, null=True)),
                ('historico', jsonfield.fields.JSONField()),
                ('status', models.CharField(blank=True, choices=[(b'solicitado', b'Solicitado'), (b'cancelado', b'Cancelado'), (b'entregue', b'Entregue'), (b'emprocessamento', b'EmProcessamento')], max_length=20, null=True)),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True, null=True)),
                ('origem', models.CharField(blank=True, choices=[(b'telegram', b'Telegram'), (b'fbmessenger', b'Facebook Messenger')], max_length=20, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.Loja')),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.Pedido'),
        ),
    ]
