# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20160807_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
