# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_auto_20160823_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='modificado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hora',
            field=models.TimeField(editable=False, null=True),
        ),
    ]
