# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 16:58
from __future__ import unicode_literals

from django.db import migrations
import utils.bigint


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_auto_20160824_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='id',
            field=utils.bigint.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=utils.bigint.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
