# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 18:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import utils.bigint


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_auto_20160918_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=utils.bigint.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedido.Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=utils.bigint.BigForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
