# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_auto_20160918_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=b'produto'),
        ),
    ]
