# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 11:30
from __future__ import unicode_literals

from django.db import migrations
from loja.models import *


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_auto_20161025_2236')
    ]

    operations = [
        migrations.RunSQL('alter table pedido_pedido drop foreign key pedido_pedido_loja_id_a854b71d_fk_loja_loja_id;')
    ]
