# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_dropfk_20161110_0010'),
        ('pedido', '0011_addfk_20161110_0012'),
    ]

    operations = [
    ]
