# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
